/** Practice details and destinations verified against the existing practice site. */
export const site = {
  name: "Cosmetic & Implant Dentistry Westport",
  title: "Cosmetic & Implant Dentistry Westport | Your Kansas City Dentist",
  description: "Personal dental care in Westport, Kansas City. Explore general dentistry, veneers, dental implants, and a team that takes the time to know you.",
  url: "https://cosmeticimplantdentistrywp.com/",
  locality: "Westport · Kansas City, Missouri",
  contactUrl: "/contact/",
  bookingUrl: "https://onlineappointment.carestack.com/?dn=acts&ln=1",
  phone: "(816) 388-0985",
  phoneUrl: "tel:+18163880985",
  address: "638 W 39th St",
  city: "Kansas City, MO 64111",
  directionsUrl: "https://www.google.com/maps/search/?api=1&query=Cosmetic+%26+Implant+Dentistry+Westport+638+W+39th+St+Kansas+City+MO",
  doctorsUrl: "/about/meet-the-doctors/",
  smileClubUrl: "https://smileclub.cosmeticimplantdentistrywp.com/",
  reviewsUrl: "https://www.google.com/maps/place/Cosmetic+%26+Implant+Dentistry+Westport/@39.0570643,-94.5950211,17z/data=!4m17!1m8!3m7!1s0x87c0efd0ee797cc7:0x97b8da6d79428aab!2s638+W+39th+St,+Kansas+City,+MO+64111!3b1!8m2!3d39.0570643!4d-94.5950211!16s%2Fg%2F11bw3zyctt!3m7!1s0x87c0ef6d9b022c53:0x705b2a50b4455ea1!8m2!3d39.057042!4d-94.5949824!9m1!1b1!16s%2Fg%2F11l34b22xf",
  teamUrl: "/about/meet-the-team/",
  privacyUrl: "/privacy-policy/",
  accessibilityUrl: "/accessibility/",
  paymentPlansUrl: "https://business.eve.co/prequalify?inviteUuid=58eb13c9-6976-4844-a887-1bab16822d25",
  hours: "Monday–Thursday, 9:00 AM–4:00 PM",
  // Confirm these with the practice before enabling them. See docs/round2-review.md.
  textingEnabled: false,
  heroVideoUrl: null as string | null,
  instagramUrl: null as string | null,
  facebookUrl: null as string | null,
  hipaaUrl: null as string | null,
  googleReviewCount: null as number | null,
} as const;

export const navLinks = [
  { href: "#care", label: "Our Approach" },
  { href: "#services", label: "Services" },
  { href: "#comfort", label: "Your Experience" },
  { href: "#contact", label: "Visit Us" },
] as const;

export const serviceLinks = {
  general: "/services/general-dentistry/",
  implants: "/services/dental-implants/",
  veneers: "/services/veneers/",
  whitening: "/services/teeth-whitening/",
  restoration: "/full-mouth-restoration/",
  sedation: "/sedation/",
  emergency: "/services/emergency-dentist/",
  crowns: "/services/crowns-bridges/",
  clearBraces: "/services/braces/",
} as const;

export const navigation = [
  { label: "About", links: [
    { label: "About Us", href: "/about/" },
    { label: "Meet Your Dentist", href: site.doctorsUrl },
    { label: "Meet The Team", href: site.teamUrl },
    { label: "Your Experience", href: "/#comfort" },
    { label: "Specials", href: "/about/specials/" },
    { label: "Smile Club", href: site.smileClubUrl },
    { label: "Payment Plans", href: site.paymentPlansUrl },
    { label: "Contact Us", href: site.contactUrl },
    { label: "Leave A Review", href: "/review/" },
  ] },
  { label: "Services", links: [
    { label: "All Our Services", href: "/services/" },
    { label: "General Dentistry", href: serviceLinks.general },
    { label: "Emergency Dentistry", href: serviceLinks.emergency },
    { label: "Teeth Cleaning", href: "/services/teeth-cleaning/" },
    { label: "Fillings", href: "/services/fillings/" },
    { label: "Mouth Guards", href: "/services/mouth-guards/" },
    { label: "Dental Implants", href: serviceLinks.implants },
    { label: "Crowns & Bridges", href: serviceLinks.crowns },
    { label: "Veneers", href: serviceLinks.veneers },
    { label: "Teeth Whitening", href: serviceLinks.whitening },
    { label: "Sleep Apnea", href: "/services/sleep-apnea/" },
    { label: "TMJ / TMD", href: "/services/tmj-tmd/" },
    { label: "Clear Braces", href: serviceLinks.clearBraces },
    { label: "Full Mouth Restoration", href: serviceLinks.restoration },
    { label: "Sedation", href: serviceLinks.sedation },
  ] },
  { label: "Problems We Treat", links: [
    { label: "Missing Teeth", href: serviceLinks.implants },
    { label: "Damaged Teeth", href: serviceLinks.restoration },
    { label: "Stained Teeth", href: serviceLinks.whitening },
    { label: "Dental Anxiety", href: serviceLinks.sedation },
    { label: "Emergency Dentistry", href: serviceLinks.emergency },
  ] },
] as const;
